---
- name: Switches configuration requirements
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Install required packages
      ansible.builtin.pip:
        name:
          - paramiko
          - ncclient

- name: Switches configuration
  hosts: switches
  gather_facts: false
  roles:
    - switch_config
